# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: < Tudo Programado Blog />
email: rafaelsanches123@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Bem-vindo ao Tudo Programado Blog!
  Aqui você encontrará uma coleção de artigos e insights sobre Inteligência Artificial, Desenvolvimento de Software e Ciência de Dados em suas diversas subáreas. Meu objetivo é compartilhar conhecimento técnico e prático, cobrindo temas que vão desde Algoritmos de Machine Learning até práticas de DevOps e Engenharia de Dados. Além disso, abordo conceitos de gestão de projetos e metodologias ágeis, oferecendo uma visão completa sobre como liderar equipes e entregar projetos com eficiência. Acompanhe e se inspire para elevar suas habilidades e conhecimentos!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rafaelsanches123.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: RafaelFVSanches
github_username:  rafaelsanches123
linkedin_username: rafael-sanches-24a2b034
#instagram_username: tudoprogramado.blog.br
#facebook_username: rafael.sanches.566
#pinterest_username: rafaelsanches56
youtube_username: UCdYowNvkN_koAAupvQOz6Lw
google_analytics: G-S4WXDJVLK3

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title
theme: minima
#plugins:
gems: #plugins -> gems in new version about jekyll
  - jekyll-feed
  - jekyll-sitemap
#  - jekyll-paginate

sass:
  quiet_deps: true

#about jekyll-paginate
#paginate: 5
#paginate_path: "/blog/page:num/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
